# Generated by Django 4.2 on 2024-05-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flas',
            new_name='Flan',
        ),
    ]
