# Generated by Django 4.2 on 2024-05-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_contactform_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
